language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
    secure: E6TO3mMHLo1JVATYtuYeNPBki0mZr4CP8ALhm0j1RLLY5mmS8NJg326uOYUbJATMGomuWDg8/si6VQJky4JTEenFeFaX4s/sXf9qVymd5PWjIAxNh6gMeT0r0Pp0gx3CZXndGkdcgg96gH16ia57EiX0SRApkdDn0sUaiIaUfUhF2v+MHTB6NkHqymB4SdXUoELlL8Sl1QZh6kAFkAUECiCTfav8lJjm1BAvtxdzAqBiBY4QRAl3ALMKFGs9wYA8gHOFLfJUrqE4YXDf8q6rpuG766E+EnXEvxIUrfVxHWNl8tdM2smh6sF4H8zpApQ3ACIr9BFbbNY/L077JLplLNs1yR5dZ2H/K1e0Q9we13VT3UqfvbugNN9R4ehEkXzBCSwWUelhn8dJwuzv7wisVhZRhS5mSZUw+j9UIs342Hb7AGSesdzDh+95nPXmsYvX9GWqY6zaxIpLfs9+QIpfstlzzY5iWaDDmHNH9z10yCOPwN595hPy0j7OmHi8hUTzh+ulZvieM87kOLM7D/9XvDEcs8eoVZBi5g1+QCNnpU845VtL+tvKo8uf1eCgjBqNg2zxXvyU6hQMnNBgDXvrmrFlJWX/bGlJ3CQk5rSHKQnrxj+/zRSl0vRVcFxv2K99pDiMNiWcZ/+xsMdlkPZo1Gs6yhHn3QIT1N054drX8Mk=
